Jashkumar Patel     
991806277

In this exercise you are going to download and examine a csv file.  Produce output for the statements below.  You are required to look up some of the dataframe commands to get the answers as not all commands were covered in the lecture.

Start by importing the appropriate libraries and downloading the dataset from: <br>
https://www.kaggle.com/datasets/arnabchaki/data-science-salaries-2023
<br>
Read the file into a dataframe

In [ ]:
import pandas as pd
import numpy as np   


df = pd.read_csv("ds_salaries.csv")

display the first 5 records of the dataframe

In [56]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M

Display the info of the dataframe

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           3755 non-null   int64
 1   experience_level    3755 non-null   object
 2   employment_type     3755 non-null   object
 3   job_title           3755 non-null   object
 4   salary              3755 non-null   int64
 5   salary_currency     3755 non-null   object
 6   salary_in_usd       3755 non-null   int64
 7   employee_residence  3755 non-null   object
 8   remote_ratio        3755 non-null   int64
 9   company_location    3755 non-null   object
 10  company_size        3755 non-null   object
dtypes: int64(4), object(7)
memory usage: 322.8+ KB

What is the number of unique values under each category?

In [58]:
df.nunique()

work_year                4
experience_level         4
employment_type          4
job_title               93
salary                 815
salary_currency         20
salary_in_usd         1035
employee_residence      78
remote_ratio             3
company_location        72
company_size             3
dtype: int64

How many of these employees have residence in Canada?

In [59]:
df[df['employee_residence'] == 'CA']

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M
7,2023,SE,FT,Data Scientist,219000,USD,219000,CA,0,CA,M
8,2023,SE,FT,Data Scientist,141000,USD,141000,CA,0,CA,M
29,2023,SE,FT,Data Strategist,90000,USD,90000,CA,0,CA,M
...,...,...,...,...,...,...,...,...,...,...,...
3604,2021,SE,FT,Data Scientist,130000,CAD,103691,CA,100,CA,L
3608,2021,MI,FT,Research Scientist,80000,CAD,63810,CA,100,CA,M
3645,2021,SE,FT,Data Analyst,90000,CAD,71786,CA,100,CA,M
3653,2021,SE,FT,Research Scientist,120500,CAD,96113,CA,50,CA,L
3714,2021,SE,FT,Data Scientist,110000,CAD,87738,CA,100,CA,S

Create a dataframe of just Canadian residence called CanDF

In [60]:
Candf = df[df['employee_residence'] == 'CA']

What is the min, max, and average salary for your CanDF?

In [61]:
print(Candf['salary_in_usd'].min())
print(Candf['salary_in_usd'].max())
print(Candf['salary_in_usd'].mean())

10000
275000
132222.90588235293

Using iloc Display the record of the highest paid employee in CanDF

In [62]:
CanDF = df[df['employee_residence'] == 'CA']

print(CanDF.iloc[CanDF['salary_in_usd'].values.argmax()])

work_year                     2022
experience_level                SE
employment_type                 FT
job_title             AI Developer
salary                      275000
salary_currency                USD
salary_in_usd               275000
employee_residence              CA
remote_ratio                     0
company_location                CA
company_size                     S
Name: 323, dtype: object