# Week 4 - Exercise
### Notebook created by Jonathan Penava

In this exercise you are going do a logistic data analysis on a data set and attempt to interpret the outcome for a specific record.<br><br>
Use the data set found on https://www.kaggle.com/datasets/dileep070/heart-disease-prediction-using-logistic-regression.  The file is attached called "framingham.csv".

Follow the steps for doing a logistic regression.  For step 7 use the following information to determine if this person is likely to develop heart disease in the next 10 years.

male                 1
age                 50
education            2
currentSmoker        1
cigsPerDay           9
BPMeds               0.0
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol            236
sysBP              132
diaBP               82
BMI                 25
heartRate           75
glucose             82

Note: You should be using all of the columns and not dropping any.  If columns are missing then you will not get full marks.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
fg =pd.read_csv("framingham.csv")

In [63]:
fg.head(50)

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
5,0,43,2.0,0,0.0,0.0,0,1,0,228.0,180.0,110.0,30.30,77.0,99.0,0
6,0,63,1.0,0,0.0,0.0,0,0,0,205.0,138.0,71.0,33.11,60.0,85.0,1
7,0,45,2.0,1,20.0,0.0,0,0,0,313.0,100.0,71.0,21.68,79.0,78.0,0
8,1,52,1.0,0,0.0,0.0,0,1,0,260.0,141.5,89.0,26.36,76.0,79.0,0
9,1,43,1.0,1,30.0,0.0,0,1,0,225.0,162.0,107.0,23.61,93.0,88.0,0
10,0,50,1.0,0,0.0,0.0,0,0,0,254.0,133.0,76.0,22.91,75.0,76.0,0
11,0,43,2.0,0,0.0,0.0,0,0,0,247.0,131.0,88.0,27.64,72.0,61.0,0
12,1,46,1.0,1,15.0,0.0,0,1,0,294.0,142.0,94.0,26.31,98.0,64.0,0
13,0,41,3.0,0,0.0,1.0,0,1,0,332.0,124.0,88.0,31.31,65.0,84.0,0
14,0,39,2.0,1,9.0,0.0,0,0,0,226.0,114.0,64.0,22.35,85.0,NaN,0
15,0,38,2.0,1,20.0,0.0,0,1,0,221.0,140.0,90.0,21.35,95.0,70.0,1
16,1,48,3.0,1,10.0,0.0,0,1,0,232.0,138.0,90.0,22.37,64.0,72.0,0
17,0,46,2.0,1,20.0,0.0,0,0,0,291.0,112.0,78.0,23.38,80.0,89.0,1
18,0,38,2.0,1,5.0,0.0,0,0,0,195.0,122.0,84.5,23.24,75.0,78.0,0
19,1,41,2.0,0,0.0,0.0,0,0,0,195.0,139.0,88.0,26.88,85.0,65.0,0
20,0,42,2.0,1,30.0,0.0,0,0,0,190.0,108.0,70.5,21.59,72.0,85.0,0
21,0,43,1.0,0,0.0,0.0,0,0,0,185.0,123.5,77.5,29.89,70.0,NaN,0
22,0,52,1.0,0,0.0,0.0,0,0,0,234.0,148.0,78.0,34.17,70.0,113.0,0
23,0,52,3.0,1,20.0,0.0,0,0,0,215.0,132.0,82.0,25.11,71.0,75.0,0
24,1,44,2.0,1,30.0,0.0,0,1,0,270.0,137.5,90.0,21.96,75.0,83.0,0
25,1,47,4.0,1,20.0,0.0,0,0,0,294.0,102.0,68.0,24.18,62.0,66.0,1
26,0,60,1.0,0,0.0,0.0,0,0,0,260.0,110.0,72.5,26.59,65.0,NaN,0
27,1,35,2.0,1,20.0,0.0,0,1,0,225.0,132.0,91.0,26.09,73.0,83.0,0
28,0,61,3.0,0,0.0,0.0,0,1,0,272.0,182.0,121.0,32.80,85.0,65.0,1
29,0,60,1.0,0,0.0,0.0,0,0,0,247.0,130.0,88.0,30.36,72.0,74.0,0
30,1,36,4.0,1,35.0,0.0,0,0,0,295.0,102.0,68.0,28.15,60.0,63.0,0
31,1,43,4.0,1,43.0,0.0,0,0,0,226.0,115.0,85.5,27.57,75.0,75.0,0
32,0,59,1.0,0,0.0,0.0,0,1,0,209.0,150.0,85.0,20.77,90.0,88.0,1
33,1,61,NaN,1,5.0,0.0,0,0,0,175.0,134.0,82.5,18.59,72.0,75.0,1
34,1,54,1.0,1,20.0,0.0,0,1,0,214.0,147.0,74.0,24.71,96.0,87.0,0
35,1,37,2.0,0,0.0,0.0,0,1,0,225.0,124.5,92.5,38.53,95.0,83.0,0
36,1,56,NaN,0,0.0,0.0,0,0,0,257.0,153.5,102.0,28.09,72.0,75.0,0
37,1,52,1.0,0,0.0,0.0,0,1,1,178.0,160.0,98.0,40.11,75.0,225.0,0
38,0,42,1.0,1,1.0,0.0,0,1,0,233.0,153.0,101.0,28.93,60.0,90.0,0
39,1,36,3.0,0,0.0,0.0,0,0,0,180.0,111.0,73.0,27.78,71.0,80.0,0
40,0,43,2.0,1,10.0,0.0,0,0,0,243.0,116.5,80.0,26.87,68.0,78.0,0
41,0,41,2.0,1,1.0,0.0,0,0,0,237.0,122.0,78.0,23.28,75.0,74.0,0
42,0,52,1.0,0,0.0,1.0,0,1,0,NaN,148.0,92.0,25.09,70.0,NaN,1
43,1,54,2.0,0,0.0,0.0,0,0,0,195.0,132.0,83.5,26.21,75.0,100.0,0
44,0,53,3.0,0,0.0,1.0,0,1,1,311.0,206.0,92.0,21.51,76.0,215.0,1
45,0,49,2.0,0,0.0,0.0,0,0,0,208.0,96.0,63.0,20.68,65.0,98.0,0
46,0,65,1.0,0,0.0,0.0,0,1,0,252.0,179.5,114.0,30.47,90.0,87.0,0
47,1,46,1.0,1,20.0,0.0,0,0,0,261.0,119.0,77.5,23.59,75.0,74.0,0
48,0,63,2.0,1,40.0,0.0,0,0,0,179.0,116.0,69.0,22.15,95.0,75.0,1
49,1,36,3.0,1,20.0,NaN,0,1,0,194.0,139.0,93.0,24.33,80.0,62.0,0

In [64]:
fg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4238 non-null   int64
 1   age              4238 non-null   int64
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64
 7   prevalentHyp     4238 non-null   int64
 8   diabetes         4238 non-null   int64
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 529.9 KB

In [65]:
fg = fg.dropna()

In [66]:
X, y = fg.drop('TenYearCHD', axis=1), fg['TenYearCHD'].values

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=87)

In [68]:
from sklearn.linear_model import LogisticRegression


logmodel = LogisticRegression(max_iter=4500)
logmodel.fit(X_train,y_train)

LogisticRegression(max_iter=4500)

In [69]:
predictions = logmodel.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.86      0.99      0.92       934
           1       0.77      0.10      0.18       163

    accuracy                           0.86      1097
   macro avg       0.82      0.55      0.55      1097
weighted avg       0.85      0.86      0.81      1097

In [70]:
predictions = logmodel.predict( X_test)
logmodel.score(X_test, y_test)

0.8623518687329079

In [71]:
fg.head(20)

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
5,0,43,2.0,0,0.0,0.0,0,1,0,228.0,180.0,110.0,30.30,77.0,99.0,0
6,0,63,1.0,0,0.0,0.0,0,0,0,205.0,138.0,71.0,33.11,60.0,85.0,1
7,0,45,2.0,1,20.0,0.0,0,0,0,313.0,100.0,71.0,21.68,79.0,78.0,0
8,1,52,1.0,0,0.0,0.0,0,1,0,260.0,141.5,89.0,26.36,76.0,79.0,0
9,1,43,1.0,1,30.0,0.0,0,1,0,225.0,162.0,107.0,23.61,93.0,88.0,0
10,0,50,1.0,0,0.0,0.0,0,0,0,254.0,133.0,76.0,22.91,75.0,76.0,0
11,0,43,2.0,0,0.0,0.0,0,0,0,247.0,131.0,88.0,27.64,72.0,61.0,0
12,1,46,1.0,1,15.0,0.0,0,1,0,294.0,142.0,94.0,26.31,98.0,64.0,0
13,0,41,3.0,0,0.0,1.0,0,1,0,332.0,124.0,88.0,31.31,65.0,84.0,0
15,0,38,2.0,1,20.0,0.0,0,1,0,221.0,140.0,90.0,21.35,95.0,70.0,1
16,1,48,3.0,1,10.0,0.0,0,1,0,232.0,138.0,90.0,22.37,64.0,72.0,0
17,0,46,2.0,1,20.0,0.0,0,0,0,291.0,112.0,78.0,23.38,80.0,89.0,1
18,0,38,2.0,1,5.0,0.0,0,0,0,195.0,122.0,84.5,23.24,75.0,78.0,0
19,1,41,2.0,0,0.0,0.0,0,0,0,195.0,139.0,88.0,26.88,85.0,65.0,0
20,0,42,2.0,1,30.0,0.0,0,0,0,190.0,108.0,70.5,21.59,72.0,85.0,0

In [72]:
myTest = {
        'male':[1],
        'age':[50], 
        'education':[2],
        'currentSmoker':[1], 
        'cigsPerDay':[9], 
        'BPMeds':[0.0], 
        'prevalentStroke':[0],  
        'prevalentHyp':[0],
        'diabetes':[0],
        'totChol':[236],
        'sysBP':[132],
        'diaBP':[82],
        'BMI':[25],
        'heartRate':[75],
        'glucose':[82]
        
       }
fg = pd.DataFrame(myTest)
print(logmodel.predict(fg))

[0]